server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nagarro_merchant_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
eureka:
  client:
    healthcheck:
      enabled: true
    should-unregister-on-shutdown: true
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: refresh
